apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: j3x9syzms-nodejs 
  janus-idp.io/tekton: j3x9syzms-nodejs
  backstage.io/kubernetes-id: j3x9syzms-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: j3x9syzms-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml